spring.application.name=BootJmsProj03SenderAppObjectMessage

# Connection to activemq server
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin


# enable PTP communication
spring.jms.pub-sub-domain=false

# make all packages content as the trusted content
spring.activemq.packages.trust-all=true

